DROP TABLE IF EXISTS entries;

CREATE TABLE entries (
  id     INTEGER PRIMARY KEY AUTOINCREMENT,
  title  TEXT NOT NULL,
  'text' TEXT NOT NULL
);

CREATE TABLE users (
  id     INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL,
  password TEXT NOT NULL
);